### ISSUE TITLE
this.get('googleAnalytics').track is undefined

### ISSUE THREAD

**Issue by IliasDeros** [tsteuwer/ember-tracker#14]
Followed ReadME instructions only to encounter this **crash** on application start, where the addon attempts to `track` on `didTransition` in the  `track-transition` mixin.

I'm not sure where `track` should have been defined? Maybe the `googleAnalytics` API has been updated ?

`Ember 2.8.0`

**Comment by tsteuwer** [comment]
I'll check it out this afternoon. In the interim, could you replicate in a dummy public repository?

**Comment by IliasDeros** [comment]
Thank you @tsteuwer. The `track-transition` mixin isn't part of this repository, it's from [another google analytics plugin](https://github.com/kaliber5/ember-google-analytics) I was testing out earlier. 

Purging npm and using only `ember-tracker` works wonders

**Comment by tsteuwer** [comment]
Awesome, great to hear. Thanks!
