### ISSUE TITLE
Destructuring of `Ember.testing` will not work. 

### ISSUE THREAD

**Issue by rwjblue** [tsteuwer/ember-tracker#17]
`Ember.testing` is a getter/setter in Ember, and destructuring like this will only read its value at the time the module is evaluated. In this case, `Ember.testing` will most likely be `false` when the module is evaluated, then change to `true` _during_ the test. This behavior somewhat recently changed in https://github.com/emberjs/ember-test-helpers/pull/227 (which is included in `ember-cli-qunit@4.1.0` / `ember-qunit@3.0.0`).

I believe the fix here would be to remove the destructuring, and use `Ember.testing` directly inline.

https://github.com/tsteuwer/ember-tracker/blob/2b2c86e4b96389ce61de11c9e263ebcc36ef3f87/addon/mixins/tealium-route.js#L16-L20

https://github.com/tsteuwer/ember-tracker/blob/2b2c86e4b96389ce61de11c9e263ebcc36ef3f87/addon/mixins/tealium-route.js#L38-L40

**Comment by tsteuwer** [comment]
Will do. Thanks for the heads up @rwjblue. I wonder why GitHub never sent me an email notification about a new issue. Lol

**Comment by rwjblue** [comment]
Haha, no problem! I struggle with missing notifications too...

**Comment by tsteuwer** [comment]
Fixed in release v0.5.2.
