### ISSUE TITLE
GDPR compliance - anonymize_ip

### ISSUE THREAD

**Issue by Redsandro** [tsteuwer/ember-tracker#23]
In order to comply with European GDPR law, we need to anonymize tracking data.

[Google suggests](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization) to enable it with this simple boolean:

```js
gtag('config', '<GA_TRACKING_ID>', { 'anonymize_ip': true })
```

Or with the old  `ga` API use this [config parameter](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp):

```js
ga('set', 'anonymizeIp', true)
```

Is this possible to set currently in `ember-tracker`? If not, can we add it somewhere?

E.g.

```js
module.exports = function(environment) {
  var ENV = {
    emberTracker: {
      analyticsSettings: {
        anonymizeIp: true,
      },
    },
  },
```

That's a quick fix to be able to use `ember-tracker` in Europe. Ideally, we would be able to dynamically reset the Boolean based on user consent. E.g. `ga('set', 'anonymizeIp', false)`, but it's not necessary.

**Comment by tsteuwer** [comment]
@Redsandro , yes you can.

Use the parameter **afterCreate**. You can add your custom JavaScript there.

```
emberTracker: {
   analyticsSettings: {
      trackingId: "UA-##########-#",
      afterCreate: "ga('set', 'anonymizeIp', true);'
   }
}
```

**Comment by tsteuwer** [comment]
@Redsandro , I didn't read your comment fully apparently lol. You should be  to do this conditionally via:

```
...
googleAnalytics: Ember.inject.service('googleAnalytics')
...
someFunction: function() {
    this.get('googleAnalytics.api')('set', 'anonymizeIp', condition ? true : false);
}
```
The property `api` is on the service which holds the instance of the GA object. You should be able to do whatever you wish with it.

**Comment by Redsandro** [comment]
Ah, so `ga` == `this.get('googleAnalytics.api')`. I think that answers my question! :+1:
